- Effect: Allow
  Action:
    - kinesis:GetRecords
    - kinesis:GetShardIterator
    - kinesis:DescribeStream
    - kinesis:DescribeStreamSummary
    - kinesis:SubscribeToShard
    - kinesis:ListShards
    - kinesis:ListStreams
  Resource: !GetAtt MaxwellStream.Arn
  
- Effect: Allow
  Action:
    - secretsmanager:GetSecretValue
  Resource: "*"
