- Effect: Allow
  Action:
    - kinesis:GetRecords
    - kinesis:GetShardIterator
    - kinesis:DescribeStream
    - kinesis:DescribeStreamSummary
    - kinesis:SubscribeToShard
    - kinesis:ListShards
    - kinesis:ListStreams
  Resource: "arn:aws:kinesis:us-west-2:302137437361:stream/maxwell*"
- Effect: Allow
  Action:
    - secretsmanager:GetSecretValue
  Resource: "*"
